name: prepare-github-pages
description: Copies Allure Report, Playwright Report, Javadocs, Test Results JSON to GitHub Pages directory

inputs:
  allure-report-dir:
    description: Path to the Allure report directory
    required: true

  playwright-report-dir:
    description: Path to the Playwright report directory
    required: false

  javadoc-dir:
    description: Optional path to the Javadoc output
    required: false
  
  test-results-json-path:
    description: Test Results JSON Path
    required: false

  output-dir:
    description: Path where GitHub Pages expects files (e.g., ./site)
    required: false
    default: github-pages

runs:
  using: "composite"
  steps:
    - name: Ensure output directory exists
      run: mkdir -p "${{ inputs.output-dir }}"
      shell: bash

    - name: Copy Allure report
      run: cp -r "${{ inputs.allure-report-dir }}" "${{ inputs.output-dir }}/allure-report"
      shell: bash
  
    - name: Copy Playwright report
      run: cp -r "${{ inputs.playwright-report-dir }}" "${{ inputs.output-dir }}/playwright-report"
      shell: bash

    - name: Copy Javadocs
      if: inputs.javadoc-dir != ''
      run: cp -r "${{ inputs.javadoc-dir }}" "${{ inputs.output-dir }}/javadocs"
      shell: bash

    - name: Copy Test Results JSON
      if: ${{ inputs.test-results-json-path != '' }}
      shell: bash
      run: cp "${{ inputs.test-results-json-path }}" "${{ inputs.output-dir }}/test-results-report.json"
