name: Post Test Results to Azure DevOps
description: "Post Test Results to Azure DevOps Test Plan"

inputs:
  test-results-json:
    description: Path to Test Results JSON
    required: true

  azure-token:
    required: true
    description: 'Azure DevOps PAT Token'
  
  org-url:
    required: true
    description: 'Azure DevOps Organization URL (e.g., https://dev.azure.com/org)'
  
  project:
    required: true
    description: 'Azure DevOps Project Name'

runs:
  using: "composite"

  steps:
    - name: Install Python
      shell: bash
      run: |
        if ! command -v python3 &> /dev/null; then
          echo "Python3 not found, installing..."
          apt-get update
          apt-get install -y python3 python3-pip
        else
          echo "Python3 is already installed"
        fi

    - name: Debug paths
      shell: bash
      run: |
        echo "github.action_path = ${{ github.action_path }}"
        if [ -d "${{ github.action_path }}" ]; then
          echo "Directory exists. Listing recursively:"
          ls -R "${{ github.action_path }}"
        else
          echo "github.action_path does NOT exist!"
          echo "Listing parent of action path:"
          ls -la "$(dirname "${{ github.action_path }}")"
          echo "Listing full _actions tree:"
          ls -R /home/runner/work/_actions/NayeemJohnY/actions/
        fi
    
    - name: Install dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    
    - name: Run Script
      run: |
        python ${{ github.action_path }}/post_results.py \
          --token "${{ inputs.azure-token }}" \
          --org-url "${{ inputs.org-url }}" \
          --project "${{ inputs.project }}" \
          --test-result-json "${{ inputs.test-results-json }}"
      shell: bash
