name: Generate Allure Report with History
description: Generate Allure report by keeping history of previous runs

inputs:
  github-token:
    description: "GitHub Token for authentication"
    required: true
    
runs:
  using: "composite"
  steps:

      - name: Set up Java if JAVA_HOME is not set
        if: ${{ !env.JAVA_HOME }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Allure CLI
        if: success() || failure()
        shell: bash
        run: |
          curl -o allure-2.27.0.tgz -L https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -xzf allure-2.27.0.tgz
          mv allure-2.27.0 /opt/allure
          ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Download Allure History
        if: success() || failure()
        shell: bash
        continue-on-error: true
        run: |
          echo "Checking contents of history folder Before:"
          ls -l test-results/allure-results/history || echo "No history folder found"

          echo -e "\nContents of history.json (if present) Before:"
          if [ -f test-results/allure-results/history/history.json ]; then
            cat test-results/allure-results/history/history.json
          else
            echo "history.json not found"
          fi
          
          mkdir -p test-results/allure-results/history
          for file in history.json categories-trend.json duration-trend.json retry-trend.json; do
            curl -sfL "https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY##*/}/allure-report/history/$file" \
              -o "test-results/allure-results/history/$file" || echo "$file not found"
          done

      - name: Generate Allure Report
        if: success() || failure()
        shell: bash
        run: |
          echo "Checking contents of history folder:"
          ls -l test-results/allure-results/history || echo "No history folder found"
      
          echo -e "\nContents of history.json (if present):"
          if [ -f test-results/allure-results/history/history.json ]; then
            cat test-results/allure-results/history/history.json
          else
            echo "history.json not found"
          fi
          
          allure generate test-results/allure-results --clean -o test-results/allure-report
