name: Generate Allure Report with History
description: Generate Allure report by keeping history of previous runs
    
runs:
  using: "composite"
  steps:
      - name: Install Allure CLI
        if: success() || failure()
        shell: bash
        run: |
          curl -o allure-2.27.0.tgz -L https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -xzf allure-2.27.0.tgz
          mv allure-2.27.0 /opt/allure
          ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Checkout GitHub Pages
        uses: actions/checkout@v3
        with:
          ref: github-pages
          path: github-pages
    
      - name: Generate Allure Report
        if: success() || failure()
        shell: bash
        run: |
          if [ -d github-pages/allure-report/history ]; then
            cp -r github-pages/allure-report/history test-results/allure-results/history
            echo "Allure history copied from GitHub Pages."
          fi

          allure generate test-results/allure-results --clean -o test-results/allure-report

